name: Tag version

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged_create_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Generate New Tag
        id: generate_tag
        run: |
          latest_tag=$( steps.get_latest_tag.outputs.tag )
          echo "Last tag is ${{ latest_tag }}"
          major=$(echo $latest_tag | cut -d'.' -f1 | cut -c2-)
          minor=$(echo $latest_tag | cut -d'.' -f2)
          patch=$(echo $latest_tag | cut -d'.' -f3)
          next_version="v$(( major )).$(( minor + 1 )).$(( patch ))"
          echo "next_tag=$next_version" >> $GITHUB_OUTPUT

      - name: Create New Tag
        run: |
          echo "Next tag is ${{ steps.generate_tag.outputs.next_tag }}"

